### ISSUE TITLE
Stop using github.com/pkg/errors

### ISSUE THREAD

**Issue by vanjiii** [gardener/gardener-extension-shoot-dns-service#74]
**How to categorize this issue?**

/area TODO
/kind enhancement
/priority 3

**What would you like to be added**:
 Similar to gardener/gardener#4280 we should be using Go native error wrapping (available since GO 1.13).
```
$ grep -r '"github.com/pkg/errors"' | grep -v vendor/ | cut -f 1 -d ':' | cut -d '/' -f 1-3 | sort | uniq -c | sort
      1 pkg/apis/helper
      1 pkg/controller/lifecycle
      1 test/system/shootdns_test.go
```

**Why is this needed**:
 Getting rid of vendors in favor of using stdlib is always nice. Others seem to do this as well - kubernetes/kubernetes#103043 and containerd/console#54.

**Comment by MartinWeindel** [comment]
Package `github.com/pkg/errors` is not used directly anymore
