### ISSUE TITLE
Shoot DNS test: unsupported kubernetes version "v1.22.2"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-shoot-dns-service#87]
**How to categorize this issue?**

/area testing
/kind bug
/priority 3

**What happened**:
With `shoot-dns-service@v1.15.0` the Shoot DNS test fails against K8s v1.22 Shoot with reason:

```
  Unexpected error:
      <*fmt.wrapError | 0xc00035ce40>: {
          msg: "error discovering kubernetes version: unsupported kubernetes version \"v1.22.2\"",
          err: <*errors.errorString | 0xc0007de660>{
              s: "unsupported kubernetes version \"v1.22.2\"",
          },
      }
      error discovering kubernetes version: unsupported kubernetes version "v1.22.2"
  occurred
```

It seems that this issue is fixed on the master branch thanks to https://github.com/gardener/gardener-extension-shoot-dns-service/pull/85. So it would be nice a have a new release of shoot-dns-service where the test does not complain about the Shoot K8s version.
In longterm, if possible, the test can be adapted to do not rely on the supported K8s versions list in gardener. Similar hidden dependency was present for the networking extensions and it was resolved for example with https://github.com/gardener/gardener-extension-networking-calico/pull/111. 

**What you expected to happen**:
No similar error when running the Shoot DNS test.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.15.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by MartinWeindel** [comment]
new released version v1.16.0 does not complain about Shoot K8s version 1.22
